name: golang-app
version: 0.1.0
description: A Golang app deployed to Kubernetes

dependencies:
  - name: nginx
    version: 1.3.0

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - sealed-secret.yaml